### ISSUE TITLE
OScript support

### ISSUE THREAD

**Issue by rd-su** [gogo2/npp-darcula#2]
Hi,

Thanks for making this theme!

Can you add support for OScript? 

It's a new supported language in Notepadd++ 7.5.

Thanks

**Comment by bsobol** [comment]
@ruiumbelino  
Yes, of course.
I don't know this language, so can you provide some code samples covering as many language features as possible for testing?

**Comment by rd-su** [comment]
@gogo2 ,

I can't provide internal code, but there is this site that has few examples and tutorials.

https://greggriffiths.org/livelink/development/oscript/
http://www.oscriptadventures.com/
http://prantlf.blogspot.co.uk/2012/07/oscript-syntax-highlighting-in-pure.html

Hope this help.

Thanks

**Comment by bsobol** [comment]
@ruiumbelino It's done. If you have any more suggestions, please feel free to tell

**Comment by rd-su** [comment]
gogo2 

Great!!! :)

Sugestions: 
1. maybe it's better to have "LANGUAGE NATIVE KEYWORD OR RESERVED WORD" and "OPERATOR; EITHER SYMBOLIC OR LITERAL" in bold, like the default in Notepad++.
It's more readable.
2. "CONSTANT LITERAL" with fgColor="0080C0"

Thanks for your work!

**Comment by bsobol** [comment]
1, With bolds I prefer to stay consistent with darcula, but you can change it by yourself by setting "fontStyle" to 1.
2. As above. Changed "CONSTANT LITERAL" to #CC7832 orange
