### ISSUE TITLE
new XML syntax definition

### ISSUE THREAD

**Issue by rd-su** [gogo2/npp-darcula#6]
Hi,

The XML has a new syntax definition:

`<WordsStyle name="ENTITY" styleID="10" fgColor="000000" bgColor="FEFDE0" fontName="" fontStyle="2" fontSize="" />`

Thanks

**Comment by rd-su** [comment]
I think it should be something like this:

`<WordsStyle name="ENTITY" styleID="10" fgColor="6898BB" bgColor="2B2B2B" fontName="" fontStyle="2" fontSize="" />`

**Comment by bsobol** [comment]
updated in 7d8b5ab579864bd2501ea574d5ed4d113e0483a0
