### ISSUE TITLE
new JSON syntax

### ISSUE THREAD

**Issue by rd-su** [gogo2/npp-darcula#7]
Hi,

The JSON syntax was changed in Notepad++

From (Darcula example):
`<LexerType name="json" desc="JSON" ext="">
            <WordsStyle name="DEFAULT" styleID="11" fgColor="A9B7C6" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="NUMBER" styleID="4" fgColor="6897BB" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="">ContentScroller</WordsStyle>
            <WordsStyle name="STRING DOUBLE QUOTE" styleID="6" fgColor="6A8759" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING SINGLE QUOTE" styleID="7" fgColor="6A8759" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="BOOLEAN NULL" styleID="5" fgColor="CC7832" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" keywordClass="instre1">endfunction endif</WordsStyle>
            <WordsStyle name="OPERATOR" styleID="10" fgColor="A9B7C6" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
        </LexerType>
		`

To (new Default example):
`<LexerType name="json" desc="JSON" ext="">
            <WordsStyle name="DEFAULT" styleID="0" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="NUMBER" styleID="1" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING" styleID="2" fgColor="800000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRINGEOL" styleID="3" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="PROPERTYNAME" styleID="4" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="ESCAPESEQUENCE" styleID="5" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="LINECOMMENT" styleID="6" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="BLOCKCOMMENT" styleID="7" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATOR" styleID="8" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="URI" styleID="9" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMPACTIRI" styleID="10" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="KEYWORD" styleID="11" fgColor="18AF8A" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre1"/>
            <WordsStyle name="LDKEYWORD" styleID="12" fgColor="FF0000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="instre2" />
            <WordsStyle name="ERROR" styleID="13" fgColor="FFFF80" bgColor="FF0000" fontName="" fontStyle="0" fontSize="" />
        </LexerType>`

If you can update it. Thanks!

**Comment by rd-su** [comment]
Maybe this:

`<LexerType name="json" desc="JSON" ext="">
            <WordsStyle name="DEFAULT" styleID="0" fgColor="A9B7C6" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="NUMBER" styleID="1" fgColor="6897BB" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING" styleID="2" fgColor="6A8659" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRINGEOL" styleID="3" fgColor="6A8659" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="PROPERTYNAME" styleID="4" fgColor="9876AA" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="ESCAPESEQUENCE" styleID="5" fgColor="CC7832" bgColor="2B2B2B" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="LINECOMMENT" styleID="6" fgColor="808080" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="BLOCKCOMMENT" styleID="7" fgColor="808080" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATOR" styleID="8" fgColor="A9B7C6" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="URI" styleID="9" fgColor="808080" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMPACTIRI" styleID="10" fgColor="808080" bgColor="2B2B2B" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="KEYWORD" styleID="11" fgColor="CC7832" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" keywordClass="instre1">True False</WordsStyle>
            <WordsStyle name="LDKEYWORD" styleID="12" fgColor="A9B7C6" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" keywordClass="instre2" />
            <WordsStyle name="ERROR" styleID="13" fgColor="A9B7C6" bgColor="2B2B2B" fontName="" fontStyle="0" fontSize="" />
        </LexerType>`

**Comment by bsobol** [comment]
updated in 8f9c9b2421e3bef11df44c8f1e3c745f26e05994
