### ISSUE TITLE
Don't double our trouble

### ISSUE THREAD

**Issue by e-motiv** [gogo2/npp-darcula#9]
Just to make sure we, developers, are not doubling efforts, wanted to let you know of this one, that includes most (or all?) formats too:

[Dracula](https://draculatheme.com/notepad-plus-plus)

(Although I like your style better, but maybe some things can be copied from each other or maybe that's already the basis of the JetBeans one and I'm sorry to waste your time)

**Comment by bsobol** [comment]
Dracula is completely diferent theme (well, except that both are dark). Darcula is based on theme available in JetBrains IDEs, which I use daily. I created this one to have a consistent theme across editors. Altought I admit it needs some adjustments for newest versions fo npp. I'll try to push some fixes soon.
